apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: chat-app
  name: chat-app-front
  labels:
    app: chat-app-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app-front
  template:
    metadata:
      labels:
        app: chat-app-front
    spec:
      containers:
      - name: chat-app-front
        image: drw.aurbac.dev/highland-cattle-chat/web-client:1.01
        ports:
        - name: chat-app
          containerPort: 80
        resources:
          limits:
            memory: "64Mi"         
---
apiVersion: v1
kind: Service
metadata:
  namespace: chat-app
  name: chat-app-front
  labels:
    app: chat-app-front
spec:
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  selector:
    app: chat-app-front